In [2]:
#ESERCIZIO
#ABBIAMO UNA LISTA DI LISTE
#CHE TIPO DI STRUTTURA DATI O MATEMATICA POTREBBE RAPPRESENTARE? NOTARE CHE TUTTE LE LISTE INTERNE SONO DELLA STESSA DIMENSIONE
#COME FACCIAMO PER ACCEDERE AD UN ELEMENTO IN PARTICOLARE

mat = [[0,1,2,3,4],
       [5,6,7,8,9],
       [10,11,12,13,14]]

       #1. Potrebbe rappresentare una matrice o tabella di dati, dato che ha una lunghezza fissa di colonne
       #2. Per accedervi basta inserire "mat" + [indice della riga , 0,1,2] + [indice della colonna , 0,1,2,3,4,5]

      #esempio. voglio mat = 11

mat[2][1]

11

In [10]:
#IMPORTIAMO IL MODULO MATH E PROVIAMO A USARE LE FUNZIONI:
#SIN() , COS() , FACTORIAL()
#E LA VARIABILE: .PI

import math

print("seno di pi greco:", math.sin(math.pi)) 
print("coseno di 0:", math.cos(0)) 
print("fattoriale di 4:", math.factorial(4))

seno di pi greco: 1.2246467991473532e-16
coseno di 0: 1.0
fattoriale di 4: 24


In [17]:
#PROVIAMO A ESEGUIRE: MATH.DEGREES(MATH.PI)
#QUAL E' E COSA SIGNIFICA IL RISULTATO?
#PER SAPERNE DI PIU' POSSIAMO USARE HELP(MATH.DEGRESS)

import math
math.degrees(math.pi)
help(math.degrees)


#1. Il risultato è 180 e corrisponde alla conversione di un angolo da radianti a gradi, come da spiegazione di help(...)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [41]:
#L'AZIENDA HA CREATO UNA LISTA DI QUANTI OGGETTI HA VENDUTO OGNI MESE NELL'UTLIMO ANNO
#TRASFORMIAMOLA IN UN ARRAY NUMPY(CASTING)
#QUAL E' STATA LA VENDITA MASSIMA MENSILE? E QUELLA MINIMA?
#QUALI SONO LE VENDITE MENSILI MAGGIORI DI 4999 OGGETTI? E QUANTE NE SONO?
#QUALI SONO LE VENDITE MINORI DI 3000 OGGETTI?
#IN MEDIA QUANTI OGGETTI SONO STATI VENDUTI AL MESE?

import numpy as np

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
arr = np.array(lst)
print(arr)

#1. Vendita Max Mensile e Minima
mas = arr.max()
print ("La vendita max mensile è stata di:",mas)
min = arr.min()
print ("La vendita min mensile è stata di:", min)

#2. Vendite > 4999
mag = arr[arr>4999]
print ("Le vendite mensili maggiori di 4999 sono:",mag)
conto = mag.size
print ("Sono:",conto)

#3. Vendite < 3000
meno = arr[arr<3000]
print ("Le vendite mensili minori di 3000 sono:",meno)

#4. Media vendite
media = arr.mean()
print ("La media delle vendite corrisponde a:", media)


[2000 5500 7200 4320 1280 1900 2500 3900 6410 8150 7100 5350]
La vendita max mensile è stata di: 8150
La vendita min mensile è stata di: 1280
Le vendite mensili maggiori di 4999 sono: [5500 7200 6410 8150 7100 5350]
Sono: 6
Le vendite mensili minori di 3000 sono: [2000 1280 1900 2500]
La media delle vendite corrisponde a: 4634.166666666667


In [48]:
#CONSIDERIAMO IL SEGUENTE DIZIONARIO (FATTURATI_DICT)
#CONSIDERIAMO LA SEGUENTE SERIES (FATTURATI_SERIES)
#POSSIAMO ACCEDERE ALLE STESSE INFORMAZIONI NELLO STESSO MODO: 
#FATTURATI_DICT[1997]
#FATTURATI_SERIES[1997]
#DUNQUE QUAL E' LA DIFFERENZA TRA I DUE TIPI DI DATO?
#COSA POSSIAMO FARE CON LA SERIES CHE NON POSSIAMO FARE CON IL DIZIONARIO?

import pandas as pd

fatturati_dict = {1997: 12_000,
                 1998: 15_000,
                 1999: 20_000,
                 2000: 23_000,
                 2001: 25_000,
                 2002: 17_000,
                 2003: 14_000,
                 2004: 21_000}

fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997,2005))

fatturati_dict[1997]
fatturati_series[1997]   

#La differnza sta nelle funzionalità che offrono. La Series offre tante funzionalita extra rispetto alla Dict.
#Es. Operazioni matematiche, Statistiche, conversione in DataFrame



12000

In [56]:
#L'AZIENDA HA UN DATASET CON TUTTI GLI STIPENDI DEI DIPENDENTI MEMORIZZATO IN UN NDARRAY:
#L'AZIENDA CI CHIEDE DI RADDOPPIARE TUTTI GLI STIPENDI; FACCIAMOLO IN DUE MODI: CICLO FOR 

import numpy as np
stipendi = np.array ([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
raddoppio = []

for stipendio in stipendi:
    raddoppio.append(stipendio * 2)

raddoppio = np.array(raddoppio)
print (raddoppio)


[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [58]:
#L'AZIENDA HA UN DATASET CON TUTTI GLI STIPENDI DEI DIPENDENTI MEMORIZZATO IN UN NDARRAY:
#L'AZIENDA CI CHIEDE DI RADDOPPIARE TUTTI GLI STIPENDI; FACCIAMOLO IN DUE MODI: MASKING

import numpy as np
stipendi = np.array ([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

maschera = stipendi > 0
stipendi[maschera] = stipendi[maschera] * 2
print (stipendi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
